### ISSUE TITLE
Doesn't retry failed tests

### ISSUE THREAD

**Issue by lucas-nguyen-17** [rajatt95/MasterRestAssuredFramework#6]
After refactoring setting `listeners` in testng.xml file, the feature re-run faileds test doesn't work.

**Reason**
```
@Listeners(value = {AnnotationTransformer.class,
		ListenerClass.class,
		MethodInterceptor.class})
public class _BaseTest {
```
Any TestNG listeners can be loaded by `@Listeners`, except `IAnnotationTransformer` --> `AnnotationTransformer.class` can't be loaded. Testng need to know `IAnnotationTransformer` earlier. Issue: https://github.com/cbeust/testng/issues/446 

**Solution**
You can choose one of 2 below approachs (both are tested):

- in testng.xml file --> have to config for each testng.xml file, and run by testng.xml file

```
<listeners>
	<listener class-name="com.spotify.oauth2.listeners.AnnotationTransformer"/>
</listeners>
```
- in maven sure-fire plugin --> have to run through `mvn clean test`

```
<property>
	<name>listener</name>
	<value>com.spotify.oauth2.listeners.AnnotationTransformer</value>
</property>
```

Two above solutions don't have same effect when running directly from IDE like Intellij.

Personally, I don't like the idea retry failed tests for API tesing because API based on stable HTTP request, it is not flaky as selenium tests. So it's up to you @rajatt95 , choose one way and I will make a pull request.

**Comment by rajatt95** [comment]
Thank you for bringing this up @lucas-nguyen-17.
IAnnotationTransformer is working only when are adding this into the testng.xml file.

Rest, in response to your suggestion - we can keep this so that if anyone can use this if it is required.
